version: "3.7"
services:
  db:
    build: ./mysql
    container_name: imageus_back_mysql
    restart: always
    ports:
      - '3333:3306'
    platform: linux/amd64
  
  imageus_back:
    build:  ./back
    container_name:  imageus_back
    depends_on:
      - db
    restart:  always
    expose:
      - "4000"

  imageus_image:
    build:  ./image_back
    container_name:  imageus_image
    depends_on:
      - db
    restart:  always
    expose:
      - "4001"
  
  nginx:
    build:  ./nginx
    container_name: nginx_imageus
    restart:  always
    ports:
      - "0.0.0.0:4000:4000"
      - "0.0.0.0:4001:4001"
    depends_on:
      - imageus_back
      - imageus_image
    platform: linux/amd64
    
  elasticsearch:
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.2
    ports:
      - 9200:9200
    restart: always
    healthcheck:
      test: curl -u elastic:elastic -s -f elasticsearch:9200/_cat/health >/dev/null || exit 1
      interval: 5s
      timeout: 3s
      retries: 50

  elasticsearch_config:
    build:  ./elasticsearch_config
    container_name: elastic_init_index
    restart: "no"
    depends_on:
      elasticsearch: 
        condition: service_healthy
    extra_hosts:
        - host.docker.internal:host-gateway 
    entrypoint: [ "bash","init_index.sh"]     