version: "3.7"
services:
  db:
    build: ./mysql
    container_name: imageus_back_mysql
    restart: always
    ports:
      - '3333:3306'
    platform: linux/amd64
  
  imageus_back:
    build:  ./back
    container_name:  imageus_back
    depends_on:
      - db
    restart:  always
    expose:
      - "4000"

  imageus_image:
    build:  ./image_back
    container_name:  imageus_image
    depends_on:
      - db
    restart:  always
    expose:
      - "4001"
  
  nginx:
    build:  ./nginx
    container_name: nginx_imageus
    restart:  always
    ports:
      - "0.0.0.0:4000:4000"
      - "0.0.0.0:4001:4001"
    depends_on:
      - imageus_back
      - imageus_image
    platform: linux/amd64
    
    